apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tos-and-thinkscript-snippet-collection
  description: TOS and Thinkscript Snippet Collection
  tags:
  - go
  - website
spec:
  type: service
  lifecycle: production
  owner: jshingler
