
=== T-USING CUSTOM COLUMN AGGREGATION



Here's an interesting concept/tip that you may find very useful and it's not obvious. The '%HL Custom Column' (available
at http://mytrade.com/StanL )  tells where, in today's prices, a stock is now i.e. 35% means it is now at 35% of today's
range (low to high). 100% means it is at its high of today's range. These numbers are based on the columns "day"
aggregation. That agg can be changed to say '4 days'. The column will then tell where in the range of the last 4 days, the
stock currently is. Use a month agg and it will tell where in the last month's range the stock currently is. The same
concept applies to all aggs. Isn't that neat? And it is so easy to change the agg. Also custom columns have some aggs that
are different from the normal chart aggs. For example 4-days is a column agg choice but is not a choice of the chart
settings (the agg dropdown).

The example used here, %HL, is a custom column study available at  http://mytrade.com/StanL Of course, you will need
to keep track of what agg you are currently using. Perhaps you can do that with the title of the custom column.
After installing the %HL you access editing it by right-clicking the watchlist column headings to customize and follow the
snapshots below:


<a name="HOW_TO_DECIPHER_COMPLEX_STUDY_PLOTS"> </a>
=== T-HOW TO DECIPHER COMPLEX STUDY PLOTS



There are some studies that have numerous plots. Deciphering what plot corresponds to particular code can be a challenge. Here is a tricky way to do it.

Here is the situation in a Edit Studies example.

In this example, if you want to identify what plot is the ORH, you uncheck 'Show Plot' and the click 'Apply'. While doing this you can observe which plot is ORH because it disappears. This can be reversed and redone if you missed the observation.This works on any highlighted plot. You can also use color changes to identify various plots.

- #end

=== T-A REFERENCE RECALL OF A STRATEGY'S RULES (SETUP)



A 'setup' is a term/title applied to a  group of charts and indicators that are used to implement a trading strategy. For example, there is a 9/30 setup that is openly discussed on the internet. Also an esteemed TS coder has written the '3X oscillator' for use specifically with the 9/30 setup.

Setups frequently have rules re what needs to exist to implement its buy/sell strategy. Such rules may be simple or complex but, regardless, are not easy to remember. This tip is to use TOS 'ThinkLog' to store those rules for easy reference. ThinkLog is accessed via the 'Tools/ThinkLog' tab and is a ready reference place where you could  refresh you memory on the implementation details of the 9/30 strategy's particulars.

=== T-FAST ACCESS TO EDITING A STUDY



The fastest way to edit a study is to double click on the plot on the chart. However, at times, clicking the right location can take many tries. This is where study highlighting can come in handy for finding the right place and time to double-click. Here is where highlighting hoovering is set:

=== T-A NEW-TO-THINKSCRIPT MUST READ



TOS has many valuable resources that may, for some, be hard to keep track of. This is a reminder of an especially valuable resource for new learners of ThinkScript as well as a refresher for you 'pros' out there. The Learning Center's 'charting/ThinkScript' ( Click here to see it ) is a must read for all newcomers to ThinkScript. Although this has three sections the 'ThinkScript Tutorials' are especially pertinent.


=== T-USING MULTIPLE TIME FRAMES TO PLAN ENTRIES



Using multiple time frames to plan entries is smart ( See Article ). To facilitate implementing a multiple-time-frame approach consider establishing a named grid with each grid component having the charts and indicators at the time frames that you are interested in. You can navigate from one grid-box to another with a single click of the grid navigation buttons. Giving the grid a name allows you to call it up whenever you want. A 'flexible grid' would be ideal for such a purpose.


=== T-WIZARD ACCESS FOR EDITING EXISTING STUDIES



When editing existing studies and you want to use the wizard, you have two choices: 1. Open a new study. Copy the wizard result via CTRL-C and then 'CANCEL' the new study; or 2. Use the wizard in the 'scan/stock hacker' and copy the wizard result via CTRL-C for pasting into the existing study editing.


=== T-PRE MARKET MOVERS



Pre market scans are not very efficient.  TOS provides a good source for pre-market movers that is accessed in the left panel by: (1) Click the + at the bottom of the left panel; (2) click 'Use The News'; and (3) Select Pre-Market Movers.

Note that the columns can be customized and adding a 'Send to [4] Green', for example, gives a quick chart of the stock.


=== T-   VERTICAL LINES AT MARKET OPEN AND CLOSED TIMES



Granted that not all personal preferences are the same. I find that frequently changing the timeframe of charts is much easier to read when I have vertical lines as market start and end times. The following code will establish those markers.

The end-time markers may seem redundant and they are if you do not 'Show Extended Session' or 'Expansion Area' for stocks. Futures and Forex are a different story.

[source]
----------------------------
#hint:Places vertical lines at start and end times
#TOS title = VertLines_at_START_END_times

input time1 = 930;
input time2 = 1630;

def StartTime = SecondsFromTime(time1) ==0;
def EndTime = SecondsFromTime(time2) ==0;

AddVerticalLine(StartTime,"Market Open",Color.RED,Curve.SHORT_DASH);
AddVerticalLine(EndTime," Market Closed",Color.RED,Curve.SHORT_DASH);
----------------------------


=== T-EASILY VIEWING CHARTS OF STOCKS IN A LIST



Comment: You have a watchlist in either the left-hand panel or in 'Market Watch/Quotes'. Wouldn't it be nice to move thru the list looking at a chart for any stock that you want. This technique is too neat not to call it to your attention herein. Here is how it's done. In the left panel:

To set the color 'Send To' buttons:

In the left panel                    In the Market Watch/Quotes          In the Market Watch/Quotes

The procedure for charting the stock is different in the two locations:

1. In the left panel, highlighting the stock will chart it:
2. In 'Market Watch/ Quotes', clicking on the 'Send To' button (in this case the green square) will chart the stock.

#end

=== T-CHANGING THE HEADER TEXT COLOR



The header text color is set to the first color definition found in the code.

Occasionally this color is hard to read if it is close to your screens background color. The following code, placed as the top lines in your study, will reset the header text color and affect nothing else except a shown below in 'edit studies'.

[source]
----------------------------
plot WhiteLabel = Double.NaN;
WhiteLabel.SetDefaultColor(Color.WHITE);#Use any color you desire
----------------------------

The above will now look like:

Note that the LinearRegCh100 color cannot be changed because it is a built-in study and its code is non-editable.

However, there are unintended consequences as shown below in this 'edit studies' screen.

#end

=== T-SEQUENCECOUNTER AND GRID UASGE



The use  of the TOS 'SequenceCounter', for intra-day trading, has an advantage when the count can be viewed to multiple aggregations simultaneously. This can be done by setting up a grid of 4 components, as an example. The below picture illustrates doing this. Also configure the chart to synchronize the cursor across all grid charts via Chart settings/general tab/Synchronize crosshair position.  A tick chart seems to present a neat plot. Regular grids is suggested in lieu of flexible grids. A picture of the setup is shown below:

Comment: The Sequence Counter is used as an example and is not a recommended indicator: reviews are not in unison.

#end

=== T-ENHANCE THE LOOKS OF A HISTOGRAM PLOT



To enhance the looks of a histogram, plot the same histogram data as a line and format that line as follows. Before and after pics are shown.

[source]
----------------------------
plot Histogram_Liner = Same data as for the histogram plot
Histogram_Liner.SetPaintingStrategy(PaintingStrategy.LINE);
Histogram_Liner.SetLineWeight(1);
Histogram_Liner.SetDefaultColor(Color.CYAN);
----------------------------


=== T-PRIVACY TO NOT SHOW ACCOUNT DOLLARS



To activate privacy that shows ***** instead of the dollar values, click the blue dot left of the 'Net Liq & Day Trades' and check the privacy square.


=== T-NAVIGATION VIA KEYBOARD HOTKEYS vs THE MOUSE



When doing a lot of coding, using the mouse provides fast traveling to various locations in the code. However, there are keyboard hotkeys that facilitate editing activities. Below is a useful list of those available in Win 7, the TS editor and most editing programs. Some are especially useful at selecting text by letter, word, line, paragraph, window, etc. Try them out and you may adopt them as your standard way of editing in combination with using the mouse.

Ctrl+C (or Ctrl+Insert)

Copy the selected item

Ctrl+X

Cut the selected item. Item cut becomes available for pasting.

Ctrl+V (or Shift+Insert)

Paste the selected item

- Ctrl+Z

- Ctrl+Y

Undo a previous action

Redo a previous action

- Delete (or Ctrl+D)

Delete the selected item and move it to the Recycle Bin

- Shift+Delete

Delete the selected item without moving it to the Recycle Bin first

- Ctrl+Right Arrow

Move the cursor to the beginning of the next word

- Ctrl+Left Arrow

Move the cursor to the beginning of the previous word

- Ctrl+Down Arrow

Move the cursor to the beginning of the next paragraph

- Ctrl+Up Arrow

Move the cursor to the beginning of the previous paragraph

- Ctrl+Shift with an arrow key

Select a block of text

- Shift with any arrow key

Select more than one item in a window or on the desktop, or select text within adocument

- Ctrl with any arrow

- key+Spacebar

Select multiple individual items in a window or on the desktop

- Ctrl+A

Select all items in a document or window

- Ctrl+Shift+Esc

Open Task Manager

- Right Arrow

- Left Arrow

- Others

Open the next menu to the right, or open a submenu

Open the next menu to the left, or close a submenu

There may be other hotkeys of interest to you at Go Here

- The free 'Notepad++' is an excellent editor made specifically for coding:   http://notepad-plus-plus.org/

- #end


=== T-THE DREADED 'TOO COMPLEX ERROR'



Custom columns run in "TOS real-time".  Additionally they have CPU performance limits (which is on their servers where all scripts run), so if your script has too much "stuff" in it and is pre-analyzed to take more execution time than is allowed you get the dreaded "too complex error."

The solution is to pare the script down to its essence and apply some good ole brain power to the data. Say you have two plots (which always generates an error in custom columns, scans, and conditional orders) and seven to eight conditions shown as nine colors packed into a single column. How did you expect to display two numerical results in each single cell?

Not to mention the rainbow of colors. Not every script that works on a chart/study is worthy of putting in a custom column.

Long series of 'if conditions' also can create the 'too complex error'. You may be able to eliminate the error if you break up a long series of if-conditions into simple sub-conditions and then combine the sub-conditions into an overall 'If' statement. Another example that you may try as a work-around is as follows:

[source]
----------------------------
Cond1 = if Low[1] <= Lowest(low, 10) then 1 else 0;
Cond2 = if close > High[1] or low[2] <=lowest(low,10) then 1 else 0;
Cond3 = if close > high[2] or Low[3] <= Lowest(low, 10) then 1 else 0;
Cond4 = if close > High[3] or low[4] <= lowest(low,10) then 1 else 0;
Cond5 = if close > high[4] or low[5] <= lowest(low,10) then 1 else 0;
Cond6 = if close > high[5]  then 1 else 0;
#Plot if Sum(cond1,cond2,cond3, cond4, cond5, cond6) = 6 then ? else ?;
----------------------------


Realize also that overly complex if-conditions are only one aspect that generates the 'too complex' error.  As initially said, it could be superfluous lines in your code retained when converting a study into a custom column. For example, 'PlotName.SetPaintingStrategy(PaintingStrategy.LINE);' and 'PlotName.SetLineWeight(1);' are superfluous in a custom column but contribute to TOS' evaluation of the 'too complex error'. Remember that we are not privy to what TOS uses to evaluates the 'too complex error' but you can be sure that the presence of superfluous code lines contribute to the error. In summary, make your code compact and smart with only necessary essential lines.



=== T-DEFINING AND APPLYING CONDITIONS IN A STUDY



When developing a strategy or adding buy/sell arrows to a  chart, it is normal to have many conditions that you are considering. When you have multiple conditions, at times it is difficult to know what conditions are firing and when. This tip presents a method to sort out the confusion that may arise with multiple conditions. The below picture is used to illustrate the concept.

The concept is to define each of your conditions in the format of '1 when true' and '0 when false'. Then plot each condition. Below you see 5 conditions and plots showing when each condition is true or false ( 1 or 0). Placing the cursor over an arrow, you can see what conditions are firing (are 1, true) to produce that arrow. Conversely, if arrows are not desired at a particular location, you then will see what condition to change. The reverse is also true when desired arrows do not exist because a condition is not being triggered.

How to do this? You take your basic code study...the one that plotted the arrows, and change the 'plot' statements to 'def' statements. You change the condition-def statements to plot statements. You create a new study for each condition so it will be plotted or you may combine condition plots in a study if you are able to identify one condition from another by colors or type of plot. Also labels are valuable for clarifications.

Don't forget to delete the studies, 5 in this example, that plotted the cnditions to preclude accumulation of studies that have no further use.


=== T-NAMING COPIED BUILTIN STUDIES



There are many instances when the built-in studies are copied and reused so you may add your own features be they technical or just look-and-feel coloring. When doing so, it is suggested that you name the new study as follows:

Builtin-name + _  + your-initials. So the MACD will look like 'MACD_ME'. The benefit of doing this is that the builtin  and your modified copy stay adjacent in the list and it helps you to keep track of what you may have done two months ago.


=== T-'PERCENTAGE VIEW' ON PRICE CHARTS



This feature enables you to view price as percentage values in lieu of dollars. This is useful when assessing price changes and comparisons. For example, the percentage of a price gap can be read by setting the initial price value to 0% and reading the gap-% value at the other end of the gap. Similarly, percent differences can be read between any two bars on the chart.

There are two modes for setting the 0% location:

1. The first bar of the chart is set to 0%  as the default.
2. Any bar may then be set to the 0%

'Percentage view' may be initiated in three ways:

1. By going to 'chart settings/price axis' tab and checking the boxes per the picture below
2. Clicking the 'finger up pointer' as shown below:
3. Clicking 'style' then 'Chart Scale' to bring up the same menu as above.

Setting any bar of the chart to 0%:

While 'percentage view' is activated, place the cursor-line over the desired bar and right click.

In the menu presented, select 'Set bar as 0%'. A horizontal 0% line will appear accross the chart at the value of the selected bar's close.

To reset the chart to the original first bar's close, right click on the zero percent level line and choose 'Reset to default 0% level'.

The calculation for the percentage shown is: (current price – close price of 0%-selected-bar) / close price of 0%-selected-bar * 100.

#end


=== T-CHANGING RIGHT EXPANSION AREA SETTING



There are three ways to do this. The easiest will be listed first.

1. Using the 'pan' tool
Go to 'Drawings' and select the 'Pan' tool .
This icon will now show on the chart in lieu of the cursor. Simply hold- down the
left mouse key and drag the chart to the left for as much right-space as you want.
Return to 'drawings' and
select 'pointer' to re-establish it. The space you panned for will be recorded in 'Chart settings/time axis/expansion area'.

2. Using the chart's lower-right symbol
Click the symbol and this menu will appear:
Clicking as shown will take you to 'Chart settings/time axis' where you set the'expansion bars to the right'.

3. Using the chart settings directly
Clicking as shown will take you to 'Chart settings/time axis' where you set the'expansion bars to the right'.


=== T-RENAMING STUDIES CAUTION



Re the recent release & Renaming studies. This feature is worthy of explanation/clarification:

If you use a study on say 15 different charts. Renaming a study will automatically change the study to the new name on each of the 15 charts. However, there are a number of places in TOS like Study Filters, Study Alerts, Custom Quotes, and Conditional orders that are allowed to use referenced studies. If the renamed study is referenced therein with the old name, then that reference(old name) will be broken i.e. will no longer work and will not be changed to the new study name. Dynamic scans are particularly vulnerable and will become ineffective if a custom referenced study is renamed.
